version: '3.3'
services:
  postgres:
    image: postgres
    container_name: teashop_db
    environment:
      POSTGRES_DB: teashop
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: on-failure
    ports:
      - "5440:5432"