services:
  prometheus:
    image: prom/prometheus:main
    user: root
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/prometheus:/prometheus"
    ports:
      - "9090:9090"

  grafana:
    build: "./config/grafana"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin