name: teashop-project
services:
  database:
    container_name: general_database
    image: postgres:17.2
    restart: on-failure
    environment:
      TZ: Europe/Kyiv
      POSTGRES_DB: teashop
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "5501:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - teashop_network

  eureka:
    container_name: eureka_service
    image: unfabled/teashop:eureka_service-0.0.2
    restart: on-failure
    networks:
      - teashop_network

  main-teashop-service:
    container_name: main_service
    image: unfabled/teashop:main_service-0.0.2
    restart: on-failure
    environment:
      BLOG_URL: ${BLOG_URL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_ADMIN: ${EMAIL_ADMIN}
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}
      GOOGLE_FOLDER_ID: ${GOOGLE_FOLDER_ID}
      GOOGLE_SHEET_RANGE: ${GOOGLE_SHEET_RANGE}
      WEBCLIENT_TIMEOUT: ${WEBCLIENT_TIMEOUT}
      SECRET_KEY: ${SECRET_KEY}
    env_file:
      - .env
    depends_on:
      eureka:
        condition: service_started
      database:
        condition: service_started
    ports:
      - "8080:8080"
      - "8888:8888"
    networks:
      - teashop_network

  order-teashop-service:
    container_name: order_service
    image: unfabled/teashop:order_service-0.0.2
    restart: on-failure
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    depends_on:
      eureka:
        condition: service_started
      database:
        condition: service_started
    networks:
      - teashop_network

  media-teashop-service:
    container_name: media_service
    image: unfabled/teashop:media_service-0.0.2
    restart: on-failure
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    depends_on:
      eureka:
        condition: service_started
      database:
        condition: service_started
    networks:
      - teashop_network

  blog-teashop-service:
    container_name: blog_service
    image: unfabled/teashop:blog_service-0.0.2
    restart: on-failure
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      WEBCLIENT_TIMEOUT: ${WEBCLIENT_TIMEOUT}
      SECRET_KEY: ${SECRET_KEY}
      TEASHOP_URL: ${TEASHOP_URL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_ADMIN: ${EMAIL_ADMIN}
      CONTACT_TRIES_THRESHOLD: ${CONTACT_TRIES_THRESHOLD}
    env_file:
      - .env
    depends_on:
      eureka:
        condition: service_started
      database:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - teashop_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/notka-teas.store/fullchain.pem:/etc/letsencrypt/live/notka-teas.store/fullchain.pem
      - /etc/letsencrypt/live/notka-teas.store/privkey.pem:/etc/letsencrypt/live/notka-teas.store/privkey.pem
      - /var/log/nginx:/var/log/nginx
    depends_on:
      eureka:
        condition: service_started
      database:
        condition: service_started
      blog-teashop-service:
        condition: service_started
      main-teashop-service:
        condition: service_started
    networks:
      - teashop_network

volumes:
  postgres-data:
    name: postgres-data

networks:
  teashop_network:
    driver: bridge